### ISSUE TITLE
Support `bsdiff` command

### ISSUE THREAD

**Issue by dreadkopp** [xpirt/sdat2img#10]
Hi,

tried to use the script on my MacbookPro without success.

installed bsdiff using lowbrow. However when i run the script i get:

./sdat2img/sdat2img.py ./update/system.transfer.list ./update/system.new.dat system.img
No valid command: bsdiff.

Installed python3.5.1 and run it with python3 -> same error

If you care to fix this and need any additional info i would be glad to help :)

Regards

**Comment by xpirt** [comment]
It seems you don't have `bsdiff` binary installed. I don't have a Mac to test, but this should install it: http://macappstore.org/bsdiff/.

Let me know.

**Comment by dreadkopp** [comment]
actually that's what i did in the first place :)

to be absolute sure i symlinked it from /usr/local/Cellar/bsdiff/4.3/bin/bsdiff to /usr/bin/bsdiff but still the same error.

**Comment by xpirt** [comment]
Oh my bad, I was wrong. The command `bsdiff` not found is in your `system_transfer_list` file. Could you post the content of your file?

Also are you trying to decompress a OTA zip file, by any chance? If so, OTAs are not supported at the moment.

**Comment by dreadkopp** [comment]
ah yes... sorry.

yes, its a OTA Update i'd like to crack open since i want to apply it without the unroot/reflash original recovery/etc madness :)

this is the system_transfer_list:

http://pastebin.com/5Uxn5qBX

Regards

**Comment by ColCh** [comment]
@xpirt works just nice on OS X El Capitan 10.11.6 using python3:

```
➜  cm-13.0-20160920-jgcaap-bacon python3 ~/.bin/sdat2img.py system.transfer.list system.new.dat system.ext4.img 

Detected system version: Android Marshmallow 6.0

Done! Output image: /Users/ColCh/Desktop/cm-13.0-20160920-jgcaap-bacon/system.ext4.img
➜  cm-13.0-20160920-jgcaap-bacon 
```

**Comment by JonnyTech** [comment]
Are there any plans to implement support for `bsdiff`? My `system.transfer.list' contains many of them:

```
user@computer:~$ ./sdat2img.py system.transfer.list system.new.dat system.img 
sdat2img binary - version: 1.0
Command "bsdiff" is not valid.
user@computer:~$ bsdiff 
bsdiff: usage: bsdiff oldfile newfile patchfile
user@computer:~$ head system.transfer.list 
4
413166
21
16431
bsdiff 0 139182 a7344d9b4816a53934e77e1b10ec5da7feb8d69c d23b0225aa408c13af68f67f903b778e1f43ab2e 2,173444,173484 99 2,319657,319756
bsdiff 139182 7158 75a48aa3a34cb0281ebf92e23b4ce1e7619b8107 a9b286227cc1722ac31a1f6beb86bbcf0d8fdbd2 2,404195,404197 7 2,229368,229375
bsdiff 146340 22878 773f427f55637f0583cb9efc9fb4818dba961228 3e4bef911c6fb5d8c6429424222853f2d4b19ca8 2,394574,394588 24 2,229278,229302
bsdiff 169218 29126 d9165bc86095e76782d34367b84f7e84871075a2 49ef979fc9b2a682a2887db6b006298e3c5c64cd 2,394589,394604 25 2,229302,229327
bsdiff 198344 19637 aa040036c82b0eefc1fe8c7ff614cbc2813c22f4 d3bafa47a9cd739c5d941433670322f727dc7791 2,126187,126193 14 2,130866,130880
bsdiff 217981 23146102 0ad49dabddca7a9a06bbd43f8fb6d4ada308a9d8 83bfcc88a442acb74deee17e6c085e4d1cab0b88 2,119455,125939 11311 2,295563,306874
user@computer:~$ 
```

**Comment by xpirt** [comment]
The aim of sdat2img is to convert sparse data into a sparse image and being able to convert it to an ext4 image afterwards.

To reproduce the patching system done by OTAs you have to patch a block image (extracted either using `sdat2img` or directly from device) on your PC using another binary, [imgpatchtools](https://github.com/erfanoabdi/imgpatchtools) by @erfanoabdi, which was made exactly for this scope.

Closed.
