### ISSUE TITLE
Close  file handler

### ISSUE THREAD

**Issue by realtebo** [xpirt/sdat2img#11]
We have a strange issue on some vps on Ubuntu server 16.04 x64. 

After execution of your script we have about 90% of memory used as cache.  
Normally OS automatically claim memory from cache when needed but in these vps this doesn't happen and so soon we get out of memory. 

We tried to analize the problem and it seems due to a lot of file handlers used by this script. The cached memory amount in fact grows while script is executing. 

I don't have enough skills to patch it so I'm asking you an help.

**Comment by xpirt** [comment]
Commit https://github.com/xpirt/sdat2img/commit/a81ab2e4d266f12c6e4703f9605eba2b2a848252 should fix this issue.
