### ISSUE TITLE
Support `move` command

### ISSUE THREAD

**Issue by mfonville** [xpirt/sdat2img#12]
When trying to apply an OTA I get:
`No valid command: move.`
any chance to implement this command to, or maybe share some insight/give some directions how it could be implemented?

**Comment by xpirt** [comment]
The aim of sdat2img is to convert sparse data into a sparse image and being able to convert it to an ext4 image afterwards.

To reproduce the patching system done by OTAs you have to patch a block image (extracted either using `sdat2img` or directly from device) on your PC using another binary, [imgpatchtools](https://github.com/erfanoabdi/imgpatchtools) by @erfanoabdi, which was made exactly for this scope.

Closed.

**Comment by reox** [comment]
Just to throw in a question here: That means a transfer file containing diff and move commands can only be fully extracted if the original `system.img` is available?
What if you ignore all the diffs and moves? Will it at least get all new files from the `system.new.dat`? Or do I always depend on the original `system.img`?
