### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ingbrzy** [xpirt/sdat2img#13]
With latest commit, you have syntax error when running file..

`sdat2img.py line 77 print('\nDetected system version: ', end=''), ^ SyntaxError: invalid syntax`

**Comment by xpirt** [comment]
Are you using Python 3?

**Comment by ingbrzy** [comment]
nope.. 2.7.5... with older file it works fine...

**Comment by xpirt** [comment]
Try using this [sdat2img.py file](https://mega.nz/#!bUVH2YzL!_K94uYCxd4JS739Ia_RajNtgXHUTtHQd0MMbOzLA7Iw) and let me know if it fixes the problem.

**Comment by ingbrzy** [comment]
thanks.. will try later..

**Comment by ColCh** [comment]
I faced this error too:

```
➜  cm-13.0-20160920-jgcaap-bacon ~/.bin/sdat2img.py system.new.dat 
  File "/Users/ColCh/.bin/sdat2img.py", line 77
    print('\nDetected system version: ', end=''),
                                            ^
SyntaxError: invalid syntax

```

But I was using python2:

```
➜  ~ python
Python 2.7.11 (default, Feb  8 2016, 12:06:00) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

```

After running `brew install python3` I succesfully launched it via: `python3`:

```
➜  cm-13.0-20160920-jgcaap-bacon python3 ~/.bin/sdat2img.py system.transfer.list system.new.dat system.ext4.img 

Detected system version: Android Marshmallow 6.0

Done! Output image: /Users/ColCh/Desktop/cm-13.0-20160920-jgcaap-bacon/system.ext4.img
```

**Comment by xpirt** [comment]
@ColCh even with the test sdat2img I uploaded?

**Comment by ColCh** [comment]
hm. no, didn't tried it. I followed ubuntu guide on the xda thread

**Comment by ingbrzy** [comment]
@xpirt ok I tried run it with python 2.7.12 and it throw this error

`/usr/bin/env: ‘python\r’: No such file or directory
Something went wrong. System.ing not generated...
`

File from  DATE: 2015-10-11 16:33:32 CST works fine
http://dpaste.com/0YQ9W4T

**Comment by xpirt** [comment]
Mmm, just update to python3. Don't think I'll continue supporting python2 anymore.

I'll close this.
