### ISSUE TITLE
Unable to unpack rom with UnicodeDecodeError

### ISSUE THREAD

**Issue by MTHD486** [xpirt/sdat2img#18]
Hi,

I tried to unpack ASUS' rom `WW_14.0400.1709.165` [from here](https://zenfonekit.weebly.com/zenfone-4-selfie-ze553kl.html).

But when I input `python sdat2img.py system.new.dat system.transfer.list system.img`, I got an error message as below:-

    sdat2img binary - version: 1.0
    Traceback (most recent call last):
      File "sdat2img.py", line 142, in <module>
        main(sys.argv)
      File "sdat2img.py", line 87, in main
        version, new_blocks, commands = parse_transfer_list_file(TRANSFER_LIST_FILE)
      File "sdat2img.py", line 58, in parse_transfer_list_file
        version = int(trans_list.readline())
      File "/usr/lib64/python3.6/codecs.py", line 321, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 1024-1025: invalid continuation byte

I tried to change line 58 from `trans_list = open(TRANSFER_LIST_FILE, 'r')` to `trans_list = open(TRANSFER_LIST_FILE, 'r', encoding = "ISO-8859-1")`, but then I got a new error message as below:-

    Traceback (most recent call last):
      File "sdat2img.py", line 142, in <module>
        main(sys.argv)
      File "sdat2img.py", line 87, in main
        version, new_blocks, commands = parse_transfer_list_file(TRANSFER_LIST_FILE)
      File "sdat2img.py", line 58, in parse_transfer_list_file
        version = int(trans_list.readline())
    ValueError: invalid literal for int() with base 10: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0

Any ideas?

Thanks in advance!

**Comment by JonnyTech** [comment]
Your file may be corrupted, download it again or find some checksums to compare its integrity.

If not then maybe it is a python 2 vs 3 incompatiblity so try running it with python 2.7.

**Comment by MTHD486** [comment]
Thanks for reply. 

For `sdat2img.py`, I copied it text-to-text directly from [here](https://github.com/xpirt/sdat2img/blob/master/sdat2img.py), so there should be no problem.

When I used Python 2.7.5 to run `python sdat2img.py system.new.dat system.transfer.list system.img`, I got this:-

    sdat2img binary - version: 1.0
    Traceback (most recent call last):
      File "sdat2img.py", line 142, in <module>
        main(sys.argv)
      File "sdat2img.py", line 87, in main
        version, new_blocks, commands = parse_transfer_list_file(TRANSFER_LIST_FILE)
      File "sdat2img.py", line 58, in parse_transfer_list_file
        version = int(trans_list.readline())
    ValueError: invalid literal for int() with base 10: ''

If I changed line 58 from `int(trans_list.readline())` to `float(trans_list.readline())`, I would get `ValueError: could not convert string to float`.

Any idea?

**Comment by JonnyTech** [comment]
Download the script from https://github.com/xpirt/sdat2img/archive/master.zip

But I meant that the system image files are corrupt.

Ah, just seen your problem: your command line is incorrect. Try `sdat2img.py system.transfer.list system.new.dat system.img`

**Comment by MTHD486** [comment]
Got it done by `python sdat2img.py system.transfer.list system.new.dat system_img`, and also successfully mount the `system_img` to `/mnt` to review.

Thanks!

**Comment by xpirt** [comment]
Seems sorted out. Closed.
