### ISSUE TITLE
You can support differential upgrade package

### ISSUE THREAD

**Issue by yfqm** [xpirt/sdat2img#8]

**Comment by xpirt** [comment]
Please provide more details..

**Comment by zeroepoch** [comment]
I just noticed the Amazon Fire TV 2 updates use imgdiff and bsdiff commands.  I think this is what they mean by incremental.  See http://amzdigitaldownloads.edgesuite.net/obfuscated-otav3-6/f1dfba6d34941c283f25b668c172c8a2/update-sloane_full_sloane-534011720-to-536116920.bin

Rename to .zip and extract to get the files.  Looking over the script you have now I believe this is quite different.
